// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRS9cdEerwAk7RlyfyGd7pW2ZDwV4ZZpI',
    appId: '1:435469706152:web:e8e68b56b873c89b7c739d',
    messagingSenderId: '435469706152',
    projectId: 'trucking-84f58',
    authDomain: 'trucking-84f58.firebaseapp.com',
    storageBucket: 'trucking-84f58.firebasestorage.app',
    measurementId: 'G-M377LN6ZY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPX-4f7qDp7XRvrVU-aXs9zXmdQCGPtEo',
    appId: '1:435469706152:android:5c6744e64e5adbf77c739d',
    messagingSenderId: '435469706152',
    projectId: 'trucking-84f58',
    storageBucket: 'trucking-84f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBTf6O3kjFaDcsMWS8JhoFZRsoU0uk61A',
    appId: '1:435469706152:ios:ac414c81c028b5857c739d',
    messagingSenderId: '435469706152',
    projectId: 'trucking-84f58',
    storageBucket: 'trucking-84f58.firebasestorage.app',
    iosBundleId: 'com.example.trucking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBTf6O3kjFaDcsMWS8JhoFZRsoU0uk61A',
    appId: '1:435469706152:ios:ac414c81c028b5857c739d',
    messagingSenderId: '435469706152',
    projectId: 'trucking-84f58',
    storageBucket: 'trucking-84f58.firebasestorage.app',
    iosBundleId: 'com.example.trucking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRS9cdEerwAk7RlyfyGd7pW2ZDwV4ZZpI',
    appId: '1:435469706152:web:985fdce2abe831bc7c739d',
    messagingSenderId: '435469706152',
    projectId: 'trucking-84f58',
    authDomain: 'trucking-84f58.firebaseapp.com',
    storageBucket: 'trucking-84f58.firebasestorage.app',
    measurementId: 'G-NNQ9B9YXR4',
  );
}
